import type { StyleOption } from './types';
import {
  AnimeIcon,
  CyberpunkIcon,
  VintageIcon,
  PixelArtIcon,
  FantasyIcon,
  WatercolorIcon,
  DoodleIcon,
  ComicIcon,
  SteampunkIcon,
  ClaymationIcon,
  MinimalistIcon,
  AbstractIcon,
  BioMechanicalIcon,
  VectorArtIcon,
  StainedGlassIcon,
  BlueprintIcon,
  PopArtIcon,
  OrigamiIcon,
} from './components/StyleIcons';

export const STYLE_OPTIONS: StyleOption[] = [
  { id: 'anime', name: 'Anime', icon: AnimeIcon, theme: 'anime' },
  { id: 'cyberpunk', name: 'Cyberpunk', icon: CyberpunkIcon, theme: 'cyberpunk' },
  { id: 'vintage-photo', name: 'Vintage', icon: VintageIcon, theme: 'vintage' },
  { id: 'pixel-art', name: 'Pixel Art', icon: PixelArtIcon, theme: 'pixel-art' },
  { id: 'fantasy-art', name: 'Fantasy', icon: FantasyIcon, theme: 'fantasy' },
  { id: 'watercolor', name: 'Watercolor', icon: WatercolorIcon, theme: 'watercolor' },
  { id: 'doodle', name: 'Doodle', icon: DoodleIcon, theme: 'doodle' },
  { id: 'comic-book', name: 'Comic', icon: ComicIcon, theme: 'comic' },
  { id: 'steampunk', name: 'Steampunk', icon: SteampunkIcon, theme: 'steampunk' },
  { id: 'claymation', name: 'Claymation', icon: ClaymationIcon, theme: 'claymation' },
  { id: 'minimalist', name: 'Minimalist', icon: MinimalistIcon, theme: 'minimalist' },
  { id: 'abstract', name: 'Abstract', icon: AbstractIcon, theme: 'abstract' },
  { id: 'vector-art', name: 'Vector Art', icon: VectorArtIcon, theme: 'vector-art' },
  { id: 'stained-glass', name: 'Stained Glass', icon: StainedGlassIcon, theme: 'stained-glass' },
  { id: 'blueprint', name: 'Blueprint', icon: BlueprintIcon, theme: 'blueprint' },
  { id: 'pop-art', name: 'Pop Art', icon: PopArtIcon, theme: 'pop-art' },
  { id: 'origami', name: 'Origami', icon: OrigamiIcon, theme: 'origami' },
  { id: 'bio-mechanical', name: 'Bio-Mechanical', icon: BioMechanicalIcon, theme: 'bio-mechanical' },
];